import { describe, expect, it } from "vitest";
import { generateMql5 } from "../src/index";
import { sampleStrategySpec } from "@prompttrader/schema";

describe("generateMql5", () => {
  it("renders a deterministic MQL5 skeleton", () => {
    const code = generateMql5(sampleStrategySpec);
    expect(code).toContain("// Generated by Prompt-to-EA Builder");
    expect(code).toContain("EvaluateEntryLong");
    expect(code).toContain("EvaluateEntryShort");
    expect(code).toContain("Spread check");
  });
});
