import {
  ConditionNode,
  IndicatorSpec,
  StrategySpec,
  ValueRef
} from "@prompttrader/schema";

const indicatorHandleName = (id: string) => `handle_${id}`;
const indicatorBufferName = (id: string) => `buf_${id}`;

const valueRefToMql = (value: ValueRef): string => {
  if (value.type === "number") {
    return value.value.toString();
  }
  if (value.type === "price") {
    const shift = value.shift ?? 0;
    return `${value.field}[${shift}]`;
  }
  const shift = value.ref.shift ?? 0;
  return `${indicatorBufferName(value.ref.id)}[${shift}]`;
};

const shiftValueRef = (value: ValueRef, shift: number): ValueRef => {
  if (value.type === "indicator") {
    return { ...value, ref: { ...value.ref, shift } };
  }
  if (value.type === "price") {
    return { ...value, shift };
  }
  return value;
};

export const compileCondition = (node: ConditionNode): string => {
  if (node.type === "group") {
    const compiled = node.conditions.map(compileCondition);
    return `(${compiled.join(` ${node.operator} `)})`;
  }
  if (node.type === "comparison") {
    return `${valueRefToMql(node.left)} ${node.operator} ${valueRefToMql(node.right)}`;
  }
  if (node.type === "cross") {
    const leftNow = valueRefToMql(node.left);
    const rightNow = valueRefToMql(node.right);
    const leftPrev = valueRefToMql(shiftValueRef(node.left, 1));
    const rightPrev = valueRefToMql(shiftValueRef(node.right, 1));
    if (node.direction === "above") {
      return `(${leftPrev} <= ${rightPrev} && ${leftNow} > ${rightNow})`;
    }
    return `(${leftPrev} >= ${rightPrev} && ${leftNow} < ${rightNow})`;
  }
  return "false";
};

const emitIndicatorSetup = (indicator: IndicatorSpec): string => {
  if (indicator.type === "SMA") {
    return `int ${indicatorHandleName(indicator.id)} = iMA(_Symbol, _Period, ${indicator.params.period}, 0, MODE_SMA, PRICE_CLOSE);`;
  }
  if (indicator.type === "EMA") {
    return `int ${indicatorHandleName(indicator.id)} = iMA(_Symbol, _Period, ${indicator.params.period}, 0, MODE_EMA, PRICE_CLOSE);`;
  }
  if (indicator.type === "RSI") {
    return `int ${indicatorHandleName(indicator.id)} = iRSI(_Symbol, _Period, ${indicator.params.period}, PRICE_CLOSE);`;
  }
  if (indicator.type === "ATR") {
    return `int ${indicatorHandleName(indicator.id)} = iATR(_Symbol, _Period, ${indicator.params.period});`;
  }
  if (indicator.type === "MACD") {
    return `int ${indicatorHandleName(indicator.id)} = iMACD(_Symbol, _Period, ${indicator.params.fast}, ${indicator.params.slow}, ${indicator.params.signal}, PRICE_CLOSE);`;
  }
  return `// Unsupported indicator ${indicator.type}`;
};

const emitIndicatorBuffers = (indicators: IndicatorSpec[]): string => {
  return indicators
    .map((indicator) => `double ${indicatorBufferName(indicator.id)}[3];`)
    .join("\n");
};

const emitIndicatorCopy = (indicators: IndicatorSpec[]): string => {
  return indicators
    .map((indicator) => `CopyBuffer(${indicatorHandleName(indicator.id)}, 0, 0, 3, ${indicatorBufferName(indicator.id)});`)
    .join("\n  ");
};

export const generateMql5 = (spec: StrategySpec): string => {
  const indicatorSetup = spec.indicators.map(emitIndicatorSetup).join("\n  ");
  const indicatorBuffers = emitIndicatorBuffers(spec.indicators);
  const indicatorCopy = emitIndicatorCopy(spec.indicators);
  const longCondition = compileCondition(spec.entryRules.long.conditions);
  const shortCondition = compileCondition(spec.entryRules.short.conditions);

  return `// Generated by Prompt-to-EA Builder\n// Strategy: ${spec.metadata.name}\n\n#property strict\n\n${indicatorBuffers}\n\nint OnInit()\n{\n  ${indicatorSetup}\n  return(INIT_SUCCEEDED);\n}\n\nvoid OnDeinit(const int reason)\n{\n}\n\nbool IsNewBar()\n{\n  static datetime lastBarTime = 0;\n  datetime currentBarTime = iTime(_Symbol, _Period, 0);\n  if(currentBarTime != lastBarTime)\n  {\n    lastBarTime = currentBarTime;\n    return true;\n  }\n  return false;\n}\n\nbool EvaluateEntryLong()\n{\n  ${indicatorCopy}\n  return ${longCondition};\n}\n\nbool EvaluateEntryShort()\n{\n  ${indicatorCopy}\n  return ${shortCondition};\n}\n\nvoid OnTick()\n{\n  if(!IsNewBar())\n  {\n    return;\n  }\n\n  // Spread check\n  double spread = (SymbolInfoDouble(_Symbol, SYMBOL_ASK) - SymbolInfoDouble(_Symbol, SYMBOL_BID)) / _Point;\n  if(spread > ${spec.constraints.maxSpread})\n  {\n    return;\n  }\n\n  if(EvaluateEntryLong())\n  {\n    // TODO: RiskSizing + PlaceOrder for long\n  }\n\n  if(EvaluateEntryShort())\n  {\n    // TODO: RiskSizing + PlaceOrder for short\n  }\n}\n`;
};
